#!/usr/bin/env python3
"""Generate the operator-support table in docs/guides/model-compatibility.md by
merging two operator sources.

Sources:
  1. scripts/data/onnx_operators.json
     The published docs.sima.ai operator table. Customer-facing source of truth
     for the precision/5D support flags (INT8 / INT16 / BF16 / 5D).
  2. skills/model_surgery/data/supported_operators.json
     The model-surgery operator database. Supplies the extra detail the
     published table lacks: ONNX opset, attributes, and implementation notes.

Merge rules:
  - Union of operators across both sources.
  - Support flags (INT8/INT16/BF16/5D): the published table wins. For operators
    that exist only in the model-sdk DB, fall back to its int8/bfloat16 values;
    INT16/5D are reported unknown.
  - Constraints column: published `constraints`, else model-sdk
    `sima_hw_sw_constraints`.
  - Notes column: model-sdk `notes`, prefixed with the ONNX opset when known.
  - Support-flag conflicts between the two sources (e.g. one says INT8=Y, the
    other INT8=N) are printed to stdout and embedded as an HTML comment at the
    top of the generated page for human review.

Run from the repo root:  python3 scripts/build_supported_operators_md.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PUBLISHED = REPO_ROOT / "scripts" / "data" / "onnx_operators.json"
MODEL_SDK = REPO_ROOT / "skills" / "model_surgery" / "data" / "supported_operators.json"
OUT = REPO_ROOT / "docs" / "guides" / "model-compatibility.md"

YES, NO, UNK = "✅", "❌", "—"


def norm_flag(value) -> str:
    """Normalize a support value to ✅ / ❌ / — (unknown)."""
    if value is None:
        return UNK
    s = str(value).strip().lower()
    if s in {"y", "yes", "true", "1"}:
        return YES
    if s in {"n", "no", "false", "0"}:
        return NO
    return UNK


def brief(text: str, limit: int = 160) -> str:
    """Trim a constraint to a brief form, cutting at a sentence/word boundary."""
    text = text.strip()
    if len(text) <= limit:
        return text
    cut = text[:limit]
    dot = cut.rfind(". ")
    if dot >= 80:
        return cut[: dot + 1] + " …"
    sp = cut.rfind(" ")
    return (cut[:sp] if sp > 0 else cut).rstrip(",;") + " …"


def fived_from_spatial(spatial) -> str:
    """Derive 5D support from the model-sdk `spatial_dimensions` string."""
    if not spatial:
        return UNK
    s = str(spatial).lower()
    if "5d" in s or "any" in s:
        return YES
    return UNK


def main() -> int:
    published = {row["operator"]: row for row in json.loads(PUBLISHED.read_text())}
    sdk_doc = json.loads(MODEL_SDK.read_text())
    sdk = sdk_doc.get("operators", {})

    names = sorted(set(published) | set(sdk), key=str.lower)
    conflicts: list[str] = []
    rows: list[tuple[str, str, str, str, str, str, str]] = []

    for name in names:
        p = published.get(name)
        m = sdk.get(name)

        # Support flags — published wins; fall back to model-sdk where absent.
        if p:
            int8 = norm_flag(p.get("int8"))
            bf16, fived = norm_flag(p.get("bfloat16")), norm_flag(p.get("fived"))
        else:
            int8 = norm_flag(m.get("int8"))
            bf16, fived = norm_flag(m.get("bfloat16")), fived_from_spatial(m.get("spatial_dimensions"))

        # Conflict detection on overlapping flags.
        if p and m:
            for flag, pv, mv in (("INT8", p.get("int8"), m.get("int8")),
                                 ("BF16", p.get("bfloat16"), m.get("bfloat16"))):
                if norm_flag(pv) != UNK and norm_flag(mv) != UNK and norm_flag(pv) != norm_flag(mv):
                    conflicts.append(f"{name}: {flag} published={pv!r} model-sdk={mv!r} (kept published)")

        # Constraints — published first, else model-sdk hardware constraints.
        constraints = ""
        if p and p.get("constraints"):
            constraints = p["constraints"]
        elif m and m.get("sima_hw_sw_constraints"):
            constraints = m["sima_hw_sw_constraints"]

        # ONNX opset — short, numeric only (skip placeholder values like "x").
        opset = ""
        if m and m.get("onnx-opset-version"):
            raw = str(m["onnx-opset-version"]).strip()
            opset = raw if raw.isdigit() else ""

        constraints = (constraints or "").replace("\n", " ").strip()
        rows.append((name, int8, bf16, fived, opset or UNK, constraints))

    lines: list[str] = [
        "---",
        "title: Model compatibility",
        "sidebar_position: 2",
        "---",
        "",
        "<!-- AUTO-GENERATED by scripts/build_supported_operators_md.py. Do not edit by hand. -->",
    ]
    if conflicts:
        lines.append("<!-- Support-flag conflicts (published table kept):")
        lines.extend(f"     - {c}" for c in conflicts)
        lines.append("-->")
    lines += [
        "",
        "# Model compatibility",
        "",
        "The SiMa.ai compilation toolchain imports **ONNX** models and prepares the "
        "operators that run on the Machine Learning Accelerator (MLA). Use this page "
        "to check whether a model's operators are supported before preparing it for "
        "Modalix.",
        "",
        "## Supported operators",
        "",
        "The table lists the operators the MLA compiler supports and the precision "
        "schemes each one runs in. **INT8** runs on the MLA; **BF16** is available on "
        "Modalix (developer preview). **5D** marks operators that accept 5D "
        "(N, D, H, W, C) tensors. **Opset** is the ONNX opset version.",
        "",
        "| Operator | INT8 | BF16 | 5D | Opset |",
        "| --- | :---: | :---: | :---: | :---: |",
    ]
    for name, int8, bf16, fived, opset, _ in rows:
        lines.append(f"| `{name}` | {int8} | {bf16} | {fived} | {opset} |")
    lines.append("")

    # Constraints as a wrapping list below the matrix, so long hardware notes
    # don't force the table wider than the page.
    constrained = [(name, c) for (name, *_rest, c) in rows if c]
    if constrained:
        lines += ["## Constraints", ""]
        for name, c in constrained:
            lines.append(f"- **{name}** — {brief(c)}")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(REPO_ROOT)} ({len(rows)} operators).")
    if conflicts:
        print(f"\n{len(conflicts)} support-flag conflict(s) (published kept):")
        for c in conflicts:
            print(f"  - {c}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
