#!/usr/bin/env python3
"""Generate docs/guides/model-compatibility.md from the canonical operator DB.

skills/model_surgery/data/supported_operators.json is the only maintained
operator-support source. It supplies support flags, 5D support, ONNX opsets,
hardware/software constraints, and implementation notes. The same constraint
field feeds the model-surgery guard and published documentation so they cannot
silently disagree.

Run from the repo root:  python3 scripts/build_supported_operators_md.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SUPPORT_DB = REPO_ROOT / "skills" / "model_surgery" / "data" / "supported_operators.json"
OUT = REPO_ROOT / "docs" / "guides" / "model-compatibility.md"

YES, NO, UNK = "✅", "❌", "—"


def norm_flag(value) -> str:
    """Normalize a support value to ✅ / ❌ / — (unknown)."""
    if value is None:
        return UNK
    s = str(value).strip().lower()
    if s in {"y", "yes", "true", "1"}:
        return YES
    if s in {"n", "no", "false", "0"}:
        return NO
    return UNK


def main() -> int:
    support_doc = json.loads(SUPPORT_DB.read_text())
    operators = support_doc.get("operators", {})
    names = sorted(operators, key=str.lower)
    rows: list[tuple[str, str, str, str, str, str]] = []

    for name in names:
        entry = operators[name]
        int8 = norm_flag(entry.get("int8"))
        bf16 = norm_flag(entry.get("bfloat16"))
        fived = norm_flag(entry.get("fived"))
        constraints = (entry.get("sima_hw_sw_constraints") or "").strip()

        # ONNX opset — short, numeric only (skip placeholder values like "x").
        opset = ""
        if entry.get("onnx-opset-version"):
            raw = str(entry["onnx-opset-version"]).strip()
            opset = raw if raw.isdigit() else ""

        rows.append((name, int8, bf16, fived, opset or UNK, constraints))

    # Payload for the OperatorTable component in the core docs site. The
    # constraint text rides along so the table's search box matches on it, even
    # though the sentences themselves render in the list below the table.
    payload = json.dumps(
        [
            {"name": name, "int8": int8, "bf16": bf16, "fived": fived,
             "opset": opset, "constraint": constraints}
            for name, int8, bf16, fived, opset, constraints in rows
        ],
        ensure_ascii=False,
        separators=(",", ":"),
    )

    lines: list[str] = [
        "---",
        "title: Model compatibility",
        "sidebar_position: 2",
        "---",
        "",
        "<!-- AUTO-GENERATED by scripts/build_supported_operators_md.py. Do not edit by hand. -->",
    ]
    lines += [
        "",
        "# Model compatibility",
        "",
        "The SiMa.ai compilation toolchain imports **ONNX** models and prepares "
        "operators for the Machine Learning Accelerator (MLA). Use this page to "
        "check operator support before you prepare a model for Modalix.",
        "",
        "## Supported operators",
        "",
        "Search the table to check MLA compiler support by operator and "
        "precision scheme. **INT8** runs on the MLA. **BF16** is available on "
        "Modalix (developer preview). **5D** marks operators that accept 5D "
        "(N, D, H, W, C) tensors. **Opset** is the ONNX opset version. Search "
        "matches constraint text as well as operator names, and each operator "
        "links to its reference on onnx.ai.",
        "",
        # Rendered by the OperatorTable component in the core docs site. The
        # payload is the element's children, and CommonMark keeps an HTML block
        # open until a blank line — so no blank lines inside these three.
        "<OperatorTable>",
        payload,
        "</OperatorTable>",
        "",
    ]

    constrained = [(name, constraints) for name, *_rest, constraints in rows if constraints]
    if constrained:
        lines += [
            "## Constraints",
            "",
            "These operators are supported with the limits below. Operators not "
            "listed here have no additional constraints. Where a constraint "
            "names an ONNX attribute, set it accordingly when you export the "
            "model.",
            "",
        ]
        for name, constraints in constrained:
            rendered_constraints = constraints.replace("\n", "<br />")
            lines.append(f"- **{name}** — {rendered_constraints}")
        lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    display_path = OUT.relative_to(REPO_ROOT) if OUT.is_relative_to(REPO_ROOT) else OUT
    print(f"Wrote {display_path} ({len(rows)} operators).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
