name: Manual Component Update PR Test

on:
  workflow_run:
    workflows:
      - Build
    types:
      - completed

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  open-component-update-pr:
    uses: sima-neat/model-compiler/.github/workflows/open-component-update-pr.yml@7878473a995c595b710b2c59a706f5bca4c61367
    secrets: inherit
