name: Schedule Component Updates

on:
  schedule:
    - cron: "17 */4 * * *"
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  update:
    uses: sima-neat/model-compiler/.github/workflows/update-components.yml@develop
    secrets: inherit
